### ISSUE TITLE
Make date format configurable

### ISSUE THREAD

**Issue by hoffmann** [inaki-ibarra/vscode-daily-notes#1]
thanks for this nice extension. Would it be possible to make the date format in the header line configurable. At the moment it uses https://github.com/inaki-ibarra/vscode-daily-notes/blob/master/extension.js#L69.

For example using  ISO 8601 format, 'YYYY-MM-DD' would be nice.

**Comment by inaki-ibarra** [comment]
> thanks for this nice extension. Would it be possible to make the date format in the header line configurable. At the moment it uses https://github.com/inaki-ibarra/vscode-daily-notes/blob/master/extension.js#L69.
> 
> For example using ISO 8601 format, 'YYYY-MM-DD' would be nice.

This is a good suggestion. I'll add this to the next release. I'm quite busy at the moment so this might take time. Feel free to submit a PR for this if you want.

**Comment by inaki-ibarra** [comment]
@hoffmann  I just released a new version [1.0.7](https://github.com/inaki-ibarra/vscode-daily-notes/releases/tag/1.0.7). Closing this issue. Thanks!
