### ISSUE TITLE
Let notes file be a relative path?

### ISSUE THREAD

**Issue by coneybeare** [inaki-ibarra/vscode-daily-notes#3]
Not sure if this is a limitation on this extension, or on VSCode itself, but I want to share notes across multiples machines so I have it living in Dropbox folder, and thus would like to set the file location to `~/Dropbox/Notes/daily-notes.md`, however this doesn't work. Is it possible to fix?

**Comment by inaki-ibarra** [comment]
The "home directory" or `~` should point to your user folder.

Can you try?
For Mac: `Users/Matt/Dropbox/Notes/daily-notes.md`
For Windows: `c:/Users/Matt/Dropbox/Notes/daily-notes.md`

**Comment by coneybeare** [comment]
Yes I agree that the ~/ should work and expand correctly, but it does not. That is the point of the issue raised. I have to hard code it with the full path in your extension, and that is the problem because the username is different on different computers.

**Comment by inaki-ibarra** [comment]
After some investigation, I can confirm that the relative path is not supported, you have to define the full path for now. If you are syncing your settings json to other computers, the relative path is very useful indeed (This shouldn't be a problem if you are using different settings json for every computer). This can be a good feature for the next release.

**Comment by inaki-ibarra** [comment]
@coneybeare I included a fix for this in version 1.0.8. Closing this issue now. Thanks.
