### ISSUE TITLE
Feature: Command add single note 

### ISSUE THREAD

**Issue by javalight** [inaki-ibarra/vscode-daily-notes#4]
This command will open a input dialogue to input a single note that will be added to the daily note file.

**Comment by inaki-ibarra** [comment]
I like to keep this extension simple since I have limited capacity but I'm curious how will this work. Can you add some use cases or scenarios where this can be useful?

**Comment by javalight** [comment]
It would look something like this
https://marketplace.visualstudio.com/items?itemName=cg-cnu.vscode-remind-me
![39146472-7e90b5c4-4754-11e8-9429-eabbc1f8c645](https://user-images.githubusercontent.com/6201595/94177440-82eedc00-fe67-11ea-9068-8234281af391.gif)

Simple input box apears, using vscode api `vscode.window.showInputBox` 

if you like i can make a pull-request. 

Would like feature to avoid having to enter into notes and finding the line to edit, the input box will allow me to quickly get my thought out of my head. Reducing cognitive load. Like when coding often we get ideas or thoughts about other areas in the project but we are in the middle of coding a different feature and cant take action. So a quick dirty note is all we need.

**Comment by inaki-ibarra** [comment]
Yeah, PRs are welcome. I think this is a good feature to add.

**Comment by inaki-ibarra** [comment]
@javalight This is now in production Version 1.0.8. Thanks for your contribution.
