### ISSUE TITLE
it`s to be an empty file

### ISSUE THREAD

**Issue by HGladiator** [inaki-ibarra/vscode-daily-notes#8]
Used for half a year, today suddenly malfunctioned, found to be an empty file. All previous records are gone, I'm using the default directory, no backups.

**Comment by HGladiator** [comment]
Before the empty file, the call button “alt+N” was used several times, only to show that the extension was starting. But the file did not appear, repeated several times, opened a blank file, but the file just closed when it was still a few hundred lines.

**Comment by inaki-ibarra** [comment]
Hi, thanks for reporting this issue. I'm using this extension myself and so far it's working fine.
I couldn't replicate what happened to you so I don't know how can I fix it. I find it weird that VSCode didn't warn you about overwriting the file. Have you tried pressing `undo` (Crtrl + Z)? There are times where you can still undo the changes even if you have closed the file.
